### ISSUE TITLE
Space travel still broken V79

### ISSUE THREAD

**Issue by twstagg** [SonicTHI/SaveOurShip2Experimental#36] opened 2023-02-05 03:22 UTC
Here is @transcendant#4142 (from Discord) log producing this error: https://discord.com/channels/537064948963082240/709868711208550422/1071524546370351104

Here is my log (twsta#3977) producing this error: https://discord.com/channels/537064948963082240/709868711208550422/1071519977468870708

```
Root level exception in Update(): System.NullReferenceException: Object reference not set to an instance of an object
  at MURWallLight.CompOffsetGlow.DespawnGlower (Verse.Map map) [0x0000f] in <2968a62b96ce46b4bfe8aca46fa5facb>:0 
  at MURWallLight.CompOffsetGlow.UpdateLit () [0x0001b] in <2968a62b96ce46b4bfe8aca46fa5facb>:0 
  at MURWallLight.CompOffsetGlow.ReceiveCompSignal (System.String signal) [0x00192] in <2968a62b96ce46b4bfe8aca46fa5facb>:0 
  at Verse.ThingWithComps.BroadcastCompSignal (System.String signal) [0x0002b] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at RimWorld.CompPowerTrader.set_PowerOn (System.Boolean value) [0x000fd] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at RimWorld.CompPowerTrader.LostConnectParent () [0x00006] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at RimWorld.CompPower.PostDeSpawn (Verse.Map map) [0x0004e] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at RimWorld.CompPowerTrader.PostDeSpawn (Verse.Map map) [0x00000] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at Verse.ThingWithComps.DeSpawn (Verse.DestroyMode mode) [0x00026] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at Verse.Building.DeSpawn (Verse.DestroyMode mode) [0x00007] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at RimWorld.Building_ShipBridge.DeSpawn (Verse.DestroyMode mode) [0x00028] in <d466b31d76ec485c9647916d8804f611>:0 
  at Verse.Thing.Destroy (Verse.DestroyMode mode) [0x00069] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at Verse.ThingWithComps.Destroy (Verse.DestroyMode mode) [0x00007] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at (wrapper dynamic-method) Verse.Building.Verse.Building.Destroy_Patch2(Verse.Building,Verse.DestroyMode)
  at RimWorld.Building_ShipBridge.Destroy (Verse.DestroyMode mode) [0x000d4] in <d466b31d76ec485c9647916d8804f611>:0 
  at SaveOurShip2.ShipInteriorMod2.MoveShip (Verse.Building core, Verse.Map targetMap, Verse.IntVec3 adjustment, RimWorld.Faction fac, System.Byte rotNum, System.Boolean includeRock, System.String writeToFile) [0x017fa] in <d466b31d76ec485c9647916d8804f611>:0 
  at SaveOurShip2.WorldSwitchUtility.SaveShip (RimWorld.Building_ShipBridge bridge) [0x00069] in <d466b31d76ec485c9647916d8804f611>:0 
  at SaveOurShip2.SaveShip.SaveShipAndRemoveItemStacks () [0x0000b] in <d466b31d76ec485c9647916d8804f611>:0 
  at (wrapper dynamic-method) RimWorld.ShipCountdown.RimWorld.ShipCountdown.CountdownEnded_Patch1()
  at RimWorld.ShipCountdown.ShipCountdownUpdate () [0x00028] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0 
  at Verse.Root_Play.Update () [0x00017] in <617d4a4b3c1842ffb4eb3fd1337f915c>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```

In some cases @transcendant#4142 had it killed his pawns, even when he had them in cryptosleep

I wasn't able to produce that behavior however, my pawns in cryptosleep were OK

Both of us also had this really weird issue as well where the ship didn't transplant all the way, and we were missing a few pieces 😂:

![image](https://user-images.githubusercontent.com/2766946/216799737-5b83d54b-8182-4d07-8095-435f1d8784b3.png)
![image](https://user-images.githubusercontent.com/2766946/216799740-6136613a-3267-48cf-9047-2341102f6b42.png)

**Comment by KentHaeger** [comment] 2023-02-06 19:26
Issues is caused by Wall Light's misbehavior when asked to despawn. Will come up with a general-purpose replacement for the other mod and remove this unwanted dependency.

**Comment by SonicTHI** [comment] 2023-03-05 01:06
Fixed with a try block as it will trigger on any non safe removed item.

**Closed by SonicTHI** 2023-03-05 01:06 UTC
